- name: Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Pull latest Docker image
      docker_image:
        name: 66026190-nextjs
        source: pull  # Ensure the latest version of the image is pulled

    - name: Create and start the container
      docker_container:
        name: 66026190-nextjs-container  # Docker container name
        image: 66026190-nextjs:latest  # Docker image name
        ports:
          - "6996:3000"  # Exposing the Docker port to host
        state: started  # Ensure the container is started
        restart_policy: always  # Ensure the container restarts automatically on failure
        volumes:
          - /path/to/your/nextjs/project:/app  # Mount the local Next.js project directory inside the container
        environment:
          - NODE_ENV=production  # Set the environment variable to production
        command: ["npm", "run", "start"]  # Start the app in production mode
